// Concatenates supabase/migrations/*.sql (in order) into supabase/ALL_MIGRATIONS.sql
// so the owner can paste a single file into the Supabase SQL editor.
// Usage: pnpm db:bundle
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const dir = join(process.cwd(), 'supabase', 'migrations');
const files = readdirSync(dir).filter((f) => /^\d{14}_.+\.sql$/.test(f)).sort();

const parts = [
  '-- ALL_MIGRATIONS.sql — GENERATED by `pnpm db:bundle`. Do not edit by hand:',
  '-- edit the numbered files in supabase/migrations/ and regenerate.',
  `-- Contains ${files.length} migrations, in order. Run once on a fresh Supabase project.`,
  '-- See supabase/APPLY.md.',
  '',
];
for (const f of files) {
  parts.push('-- ' + '='.repeat(76), `-- ${f}`, '-- ' + '='.repeat(76), readFileSync(join(dir, f), 'utf8').trimEnd(), '');
}
writeFileSync(join(process.cwd(), 'supabase', 'ALL_MIGRATIONS.sql'), parts.join('\n') + '\n');
console.log(`Wrote supabase/ALL_MIGRATIONS.sql (${files.length} migrations)`);
