// Generates supabase/demo-seed.sql from scripts/demo/content.ts.
// Usage: pnpm db:demo   (then apply demo-seed.sql; remove with demo-clear.sql)
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { renderDoc, docToText, firstParagraph, type PMNode } from '../src/lib/content/render';
import { ARTICLES, AUTHORS, DEMO_TAGS, IMAGES, type Block } from './demo/content';

const q = (s: string | null | undefined) => (s == null ? 'null' : `'${s.replace(/'/g, "''")}'`);
const j = (v: unknown) => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
const text = (t: string, marks?: PMNode['marks']): PMNode => ({ type: 'text', text: t, ...(marks ? { marks } : {}) });
const para = (t: string): PMNode => ({ type: 'paragraph', content: [text(t)] });

function toDoc(blocks: Block[]): PMNode {
  const content: PMNode[] = [];
  for (const b of blocks) {
    if (typeof b === 'string') content.push(para(b));
    else if ('h2' in b) content.push({ type: 'heading', attrs: { level: 2 }, content: [text(b.h2)] });
    else if ('quote' in b) content.push({ type: 'blockquote', content: [para(b.quote)] });
    else if ('pull' in b) content.push({ type: 'pullQuote', content: [text(b.pull)] });
    else if ('list' in b) content.push({ type: 'bulletList', content: b.list.map((i) => ({ type: 'listItem', content: [para(i)] })) });
    else if ('qa' in b) {
      content.push({ type: 'paragraph', content: [text(b.qa[0], [{ type: 'bold' }])] });
      content.push(para(b.qa[1]));
    } else if ('table' in b) {
      content.push({
        type: 'table',
        content: b.table.map((row, i) => ({
          type: 'tableRow',
          content: row.map((cell) => ({ type: i === 0 ? 'tableHeader' : 'tableCell', content: [para(cell)] })),
        })),
      });
    }
  }
  return { type: 'doc', content };
}

const uuid = (n: number) => `de200000-0000-4000-8000-${String(n).padStart(12, '0')}`;
const groupId = (n: number) => `de300000-0000-4000-8000-${String(n).padStart(12, '0')}`;

const out: string[] = [];
out.push(`-- demo-seed.sql — GENERATED by \`pnpm db:demo\` from scripts/demo/content.ts. Do not edit by hand.
-- Demo content for trying the site: ${ARTICLES.length} fictional articles, 3 demo authors (who cannot log in),
-- ${Object.keys(IMAGES).length} photos from Wikimedia Commons (credited, CC licences, loaded from upload.wikimedia.org).
-- Every row is flagged is_demo = true and every title starts with «[تجريبي]» or «[Démo]».
-- Remove everything with demo-clear.sql. Run after seed.sql. Dates are relative to now().
begin;
`);

// Authors: auth users without password (they can't log in); the trigger creates the profile.
for (const a of Object.values(AUTHORS)) {
  out.push(`insert into auth.users (id, instance_id, aud, role, email, raw_user_meta_data, raw_app_meta_data, created_at, updated_at)
values ('${a.id}', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', ${q(a.email)}, ${j({ display_name: a.name_ar, slug: a.slug })}, '{"provider":"email","providers":["email"]}'::jsonb, now(), now())
on conflict (id) do nothing;
update public.profiles set display_name_ar = ${q(a.name_ar)}, display_name_fr = ${q(a.name_fr)}, slug = ${q(a.slug)},
  title_ar = ${q(a.title_ar)}, title_fr = ${q(a.title_fr)}, bio_ar = ${q(a.bio_ar)}, bio_fr = ${q(a.bio_fr)}, is_demo = true
where id = '${a.id}';`);
}

// Media
for (const m of Object.values(IMAGES)) {
  out.push(`insert into public.media (id, storage_path, variants, mime_type, width, height, focal_x, focal_y, alt_ar, alt_fr, caption_ar, caption_fr, credit, is_demo)
values ('${m.id}', ${q(m.variants[1280]!)}, ${j({ 500: m.variants[500], 960: m.variants[960], 1280: m.variants[1280] })}, 'image/jpeg', ${m.width}, ${m.height}, ${m.focal_x ?? 0.5}, ${m.focal_y ?? 0.5},
  ${q(m.alt_ar)}, ${q(m.alt_fr)}, ${q(m.caption_ar)}, ${q(m.caption_fr)}, ${q(m.credit)}, true)
on conflict (id) do nothing;`);
}

// Demo tags
for (const t of DEMO_TAGS) {
  out.push(`insert into public.tags (kind, slug, name_ar, name_fr, is_demo) values ('${t.kind}', ${q(t.slug)}, ${q(t.name_ar)}, ${q(t.name_fr)}, true) on conflict (slug) do nothing;`);
}
out.push(`update public.tags set is_featured = true where slug in ('demo-club-menzel-temime', 'kelibia');`);

// Articles
const keyIndex = new Map(ARTICLES.map((a, i) => [a.key, i + 1]));
ARTICLES.forEach((a, i) => {
  const n = i + 1;
  const doc = toDoc(a.body);
  const html = renderDoc(doc, { locale: a.lang });
  const plain = docToText(doc);
  const img = a.image ? IMAGES[a.image] : undefined;
  const tg = a.translationOf ? groupId(keyIndex.get(a.translationOf)!) : ARTICLES.some((x) => x.translationOf === a.key) ? groupId(n) : null;
  out.push(`insert into public.articles (id, language, translation_group_id, status, title, subtitle, excerpt, body_json, body_html, body_text,
  category_id, format_id, location, cover_media_id, is_breaking, breaking_until, is_featured, is_sponsored, sponsor_name, allow_ads,
  published_at, first_published_at, correction_note_ar, created_by, is_demo)
values ('${uuid(n)}', '${a.lang}', ${tg ? `'${tg}'` : 'null'}, 'published', ${q(a.title)}, ${q(a.subtitle)}, ${q(firstParagraph(doc))},
  ${j(doc)}, ${q(html)}, ${q(plain)},
  (select id from public.categories where slug = '${a.category}'), (select id from public.article_formats where slug = '${a.format}'),
  ${q(a.location)}, ${img ? `'${img.id}'` : 'null'}, ${a.breaking ? 'true' : 'false'}, ${a.breaking ? "now() + interval '5 hours'" : 'null'},
  ${a.featured ? 'true' : 'false'}, ${a.sponsor ? 'true' : 'false'}, ${q(a.sponsor)}, ${a.sponsor ? 'false' : 'true'},
  now() - interval '${a.hoursAgo} hours', now() - interval '${a.hoursAgo} hours', ${q(a.correction)}, '${AUTHORS[a.author].id}', true)
on conflict (id) do nothing;
insert into public.article_authors (article_id, profile_id, position) values ('${uuid(n)}', '${AUTHORS[a.author].id}', 0) on conflict do nothing;`);
  for (const t of a.tags ?? []) {
    out.push(`insert into public.article_tags (article_id, tag_id) select '${uuid(n)}', id from public.tags where slug = '${t}' on conflict do nothing;`);
  }
  for (const c of a.extraCategories ?? []) {
    out.push(`insert into public.article_categories (article_id, category_id) select '${uuid(n)}', id from public.categories where slug = '${c}' on conflict do nothing;`);
  }
  if (a.correction) out.push(`update public.articles set content_updated_at = now() - interval '${Math.max(0, a.hoursAgo - 3)} hours' where id = '${uuid(n)}';`);
});

out.push(`
commit;

select (select count(*) from public.articles where is_demo) as demo_articles,
       (select count(*) from public.profiles where is_demo) as demo_authors;
`);

writeFileSync(join(process.cwd(), 'supabase', 'demo-seed.sql'), out.join('\n') + '\n');
console.log(`Wrote supabase/demo-seed.sql (${ARTICLES.length} articles)`);
